name: helplane_flutter
description: HelpLane chat widget SDK for Flutter. Add live chat support to your Flutter app.
version: 1.0.0
homepage: https://github.com/intigratech/helplane-flutter
repository: https://github.com/intigratech/helplane-flutter
issue_tracker: https://github.com/intigratech/helplane-flutter/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.helplane.flutter
        pluginClass: HelpLaneFlutterPlugin
      ios:
        pluginClass: HelpLaneFlutterPlugin
